openapi: 3.0.0
info:
  title: Task Coordinator API
  description: API documentation for task coordinator endpoints.
  version: 1.0.0
paths:
  /api/v1/tasks/coordinator/create:
    post:
      summary: Create a new task
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                task_name:
                  type: string
                  example: "Prepare Presentation"
                task_type:
                  type: string
                  example: "Meeting"
                description:
                  type: string
                  example: "Discuss project milestones."
                start_time:
                  type: string
                  format: date-time
                  example: "2024-01-10T09:00:00Z"
                end_time:
                  type: string
                  format: date-time
                  example: "2024-01-10T10:00:00Z"
                max_participants:
                  type: integer
                  example: 10
      responses:
        "201":
          description: Task successfully created
        "400":
          description: Missing required fields or invalid data
        "409":
          description: Task already exists
        "401":
          description: Unauthorized
        "500":
          description: Internal server error

  /api/v1/tasks/coordinator/assign:
    post:
      summary: Assign a task to a user
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                assignee_id:
                  type: string
                  example: "user123"
                task_id:
                  type: string
                  example: "task456"
      responses:
        "201":
          description: Assignment successfully created
        "409":
          description: Assignment already exists or assignee not free
        "400":
          description: Maximum participants reached
        "401":
          description: Unauthorized
        "500":
          description: Internal server error

  /api/v1/tasks/coordinator/delete_task/{task_id}:
    delete:
      summary: Delete a task
      security:
        - bearerAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Task successfully deleted
        "401":
          description: Unauthorized
        "500":
          description: Internal server error

  /api/v1/tasks/coordinator/delete_assignment/{assignment_id}:
    delete:
      summary: Delete an assignment
      security:
        - bearerAuth: []
      parameters:
        - name: assignment_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Assignment successfully deleted
        "401":
          description: Unauthorized
        "500":
          description: Internal server error

  /api/v1/tasks/coordinator/update_task/{task_id}:
    patch:
      summary: Update a task
      security:
        - bearerAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                task_name:
                  type: string
                  example: "Updated Task Name"
                task_type:
                  type: string
                  example: "Updated Type"
                description:
                  type: string
                  example: "Updated description."
                start_time:
                  type: string
                  format: date-time
                  example: "2024-01-11T09:00:00Z"
                end_time:
                  type: string
                  format: date-time
                  example: "2024-01-11T10:00:00Z"
                max_participants:
                  type: integer
                  example: 20
      responses:
        "200":
          description: Task successfully updated
        "401":
          description: Unauthorized
        "500":
          description: Internal server error

  /api/v1/tasks/coordinator/update_assignment/{assignment_id}:
    patch:
      summary: Update an assignment
      security:
        - bearerAuth: []
      parameters:
        - name: assignment_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                assignee_id:
                  type: string
                  example: "new_user123"
      responses:
        "200":
          description: Assignment successfully updated
        "409":
          description: Assignment already exists or assignee not free
        "401":
          description: Unauthorized
        "500":
          description: Internal server error

  /api/v1/tasks/coordinator/all_tasks:
    get:
      summary: Retrieve all tasks
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Tasks successfully retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  tasks:
                    type: array
                    items:
                      type: object
                      properties:
                        task_id:
                          type: string
                          example: "task456"
                        task_name:
                          type: string
                          example: "Sample Task"
                        task_type:
                          type: string
                          example: "Meeting"
        "401":
          description: Unauthorized
        "500":
          description: Internal server error

  /api/v1/tasks/coordinator/all_assignments:
    get:
      summary: Retrieve all assignments
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Assignments successfully retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  assignments:
                    type: object
                    additionalProperties:
                      type: object
                      properties:
                        assignment_id:
                          type: integer
                          example: 1
                        task_name:
                          type: string
                          example: "EIS Tour"
                        description:
                          type: string
                          example: "Tour guide"
                        start_time:
                          type: string
                          format: date-time
                          example: "2025-01-20T11:30:00Z"
                        end_time:
                          type: string
                          format: date-time
                          example: "2025-01-20T12:30:00Z"
                        users:
                          type: array
                          items:
                            type: object
                            properties:
                              first_name:
                                type: string
                                example: "Chizzie"
                              last_name:
                                type: string
                                example: "Mgbodille"
                              user_id:
                                type: string
                                example: "b058b8d5-a9b4-4f43-9ffd-7aedb454dbe4"
                  sorted_tasks:
                    type: array
                    items:
                      type: integer
                      example: 1
        "401":
          description: Unauthorized
        "500":
          description: Internal server error

  /api/v1/tasks/coordinator/all_users:
    get:
      summary: Retrieve all users
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Users successfully retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      type: object
                      properties:
                        user_id:
                          type: string
                          example: "user123"
                        username:
                          type: string
                          example: "johndoe"
        "401":
          description: Unauthorized
        "500":
          description: Internal server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
